### ISSUE TITLE
Mayor cannot change income tax rate

### ISSUE THREAD

**Issue by ReverendQ** [LordZZT/zRP#28]
At present, the mayoral interface just looks like this: http://i.imgur.com/4MvJ5RA.png

**Comment by LordZZT** [comment]
wait for a pay cycle to go through, then click on income tax

**Comment by ReverendQ** [comment]
That's the bug part: This was after about two hours on the server as mayor.

Oddly, when I was on tonight as mayor, it worked as expected. I guess it might have been a one-time issue.
